docs/flatpak-builder.rst
Signed-off-by: Silvio Fricke <silvio.fricke@gmail.com>
=> add a hint for json entities in man pages

docs/_static/theme_overrides.css, docs/command-reference.rst, docs/index.rst, docs/introduction.rst
Slowly getting into the sphinx mindset...
=> Make the man page integration more natural

docs/elements-of-a-flatpak-app.rst
It took me a few reads before I understood the sentence so thought I should clear it up a bit.
=> Slightly clearer wording

po/fr/LC_MESSAGES/building-simple-apps.po, po/fr/LC_MESSAGES/distributing-applications.po, po/fr/LC_MESSAGES/elements-of-a-flatpak-app.po, po/fr/LC_MESSAGES/flatpak-builder.po, po/fr/LC_MESSAGES/getting-setup.po, po/fr/LC_MESSAGES/index.po, po/fr/LC_MESSAGES/introduction.po, po/fr/LC_MESSAGES/working-with-the-sandbox.po
Fixes various typo and make better sentences
=> FR: Fixes for typo

docs/flatpak-builder.rst
Iẗ́'s not called rename-appdata.
=> Fix up reference to rename-appdata-file property

docs/available-runtimes.rst
KDE should be a sub-section, not a page.
=> available runtimes - fix section nesting

docs/index.rst, docs/using-flatpak.rst
Provide an overview of the basic commands needed to install and
manage applications.
=> add a page on basic usage

docs/introduction.rst, docs/using-flatpak.rst, images/diagram.svg
Editorial and technical review would be good.
=> Introduction improvements

docs/first-build.rst
The passive voice here is unnecessarily awkward.
=> Reword a sentence

docs/introduction.rst
These are also important goals of flatpak, and should
be mentioned here to give a full picture.
=> Add some more goals

docs/basic-concepts.rst, docs/building-basics.rst, docs/building.rst, docs/getting-started.rst, docs/introduction.rst, docs/reference.rst, docs/under-the-hood.rst
The introduction was previously a list of objectives and some
material on basic concepts. This ignored two key questions
people will have - can I use Flatpak for my app, and why should
I use Flatpak?
This commit answers those questions, and moves the previous
content elsewhere. It also fixes #110.
=> Rewrite introduction

docs/electron.rst
The steps themselves are tested to work.
Everything else I'm reasonably sure is accurate, but could be wrong.
=> Add work in progress electron guide

docs/first-build.rst, docs/hosting-a-repository.rst, docs/index.rst, docs/introduction.rst, docs/manifests.rst, docs/sandbox-permissions.rst, docs/under-the-hood.rst
The under-the-hood.rst additions would benefit from some review for technical correctness...
=> Technicalities

docs/building-basics.rst
I'm not sure if this needs technical review, but it might be nice to have feedback before merging.
=> building-basics.rst: be a guide

docs/libflatpak-api-reference.rst
This did not work as written. Try again.
=> Fix up the libflatpak docs link

docs/flatpak-docs.html
Include the html docs generated for flatpak 1.0.6.
=> Update the docs

docs/hosting-a-repository.rst
To remove any ambiguity I added 'flatpak' before build-update-repo.
=> Minor change to host-repository

docs/first-build.rst
=> Small typo fix

docs/tips-and-tricks.rst
Flatpak-bisect was introduced in
https://github.com/flatpak/flatpak/pull/575
=> tips-and-tricks: Describe how to use flatpak-bisect

docs/tips-and-tricks.rst
Copy the content from https://github.com/flatpak/flatpak/issues/1224
=> tips-and-tricks: Add a section about custom installations

docs/electron.rst, docs/first-build.rst, docs/manifests.rst, docs/python.rst, docs/qt.rst
Switch to using YAML rather than JSON in the examples, because it's
easier to read and work with. Before merging this we should get these
two PRs merged:
- https://github.com/flathub/electron-sample-app/pull/2
- https://github.com/flathub/org.gnome.Dictionary/pull/8
=> Switch to YAML

docs/manifests.rst
Fallout from 4193fc72020701edde89b5d0a7f523f370d5446b.
=> manifests: Dictionary uses YAML now

docs/sandbox-permissions.rst
Not (probably: no longer) in the introduction.
=> Portals are introduced in 'basic concepts'

docs/electron.rst
=> electron: Fix code block markup

docs/multiarch.rst
=> Add guide for building multilib apps

docs/conventions.rst
See https://github.com/flatpak/flatpak/pull/4478
=> conventions: Add info about XDG_STATE_HOME

docs/tips-and-tricks.rst
Inspired by https://github.com/flatpak/flatpak/issues/4659#issuecomment-1009437265
=> tips-and-tricks: Add systemd.resource-control instructions

docs/sandbox-permissions.rst
This documents the changes being tracked on Flathub at:
https://github.com/flathub/flathub/issues/2180
CC @owtaylor
=> Document build finish options for gvfs usage

docs/available-runtimes.rst
Apologies if I missed anything here, I didn't see anything about how to form pull requests in the README :)
This PR adds the elementary runtime to the list of available Flatpak runtimes and documents what it includes. Thanks!
=> Add the elementary to the list of available runtimes

docs/conf.py, requirements.txt
While I was able to test this locally, it doesn't seem like the debug build like instructed in the readme matches what's on the docs page.
So this would need some additional tests / clearing up of the build instructions.
=> Add dark theme

docs/_static/dark.css, docs/conf.py
@TingPing here's another try, simpler this time, based on an approach found here https://github.com/readthedocs/readthedocs.org/issues/3819#issuecomment-722654830
Lookal build seems to pick this up fine, but in general the local build seems to be quiet different from the finished page (even on master)
=> Add dark mode css

docs/conventions.rst
- See https://github.com/flathub/flathub/issues/3118
=> Clarify appstream location and name

images/diagram.svg
- use the new typeface for the diagram
See https://github.com/flatpak/flatpak.github.io/issues/537
=> diagram: use Inter font

docs/manifests.rst
Closes https://github.com/flatpak/flatpak-docs/issues/75.
=> Add flatpak-builder-tools

docs/manifests.rst
Closes https://github.com/flatpak/flatpak-docs/issues/217.
=> Add shared-modules

docs/conventions.rst
=> Very minor text fixes

docs/conventions.rst, docs/first-build.rst, docs/freedesktop-quick-reference.rst, docs/index.rst, docs/manifests.rst, docs/qt.rst, docs/repositories.rst, docs/tips-and-tricks.rst, docs/under-the-hood.rst, docs/usb-drives.rst
Brought up by sphinx-build's linkcheck target
=> Fix redirected links

docs/conventions.rst
Cf. <https://github.com/flathub/flathub/pull/3724#discussion_r1055434444>.
=> Reduce confusion over what is a valid app-id

docs/available-runtimes.rst, docs/electron.rst, docs/first-build.rst, docs/manifests.rst, docs/multiarch.rst, docs/qt.rst
These are update to newer standards of practice.
=> Update manifest examples

requirements.txt
The recent change needs this lib too, to completly work and generate social cards
=> Install matplotlib to render social previews

docs/dependencies.rst, docs/extension.rst, docs/guides.rst
Closes https://github.com/flatpak/flatpak-docs/issues/100
Closes https://github.com/flatpak/flatpak-docs/pull/349
Closes https://github.com/flatpak/flatpak-docs/issues/18
Closes https://github.com/flatpak/flatpak-docs/issues/178
Closes https://github.com/flatpak/flatpak-docs/issues/323
The first commit is a squash of the all the commits in https://github.com/flatpak/flatpak-docs/pull/349, the second two are the only modifications on top of that.
=> Create a guide and overview of flatpak extensions

docs/available-runtimes.rst
Clutter be gone for a long time now
=> sdks/gnome: Drop Clutter mention

docs/extension.rst
It works ootb now with appstreamcli
=> extension: Drop manual compose of metadata

docs/introduction.rst
Closes https://github.com/flatpak/flatpak-docs/issues/396
=> Describe some limitations of Flatpak as a packaging method

docs/sandbox-permissions.rst
This is a regular source for confusion.
Closes https://github.com/flatpak/flatpak-docs/issues/407
=> Add a note for supported combinations of display sockets

docs/sandbox-permissions.rst
Closes https://github.com/flatpak/flatpak-docs/issues/162
=> sandbox-permissions: Cover some filesystem permissions edge cases

README.rst
I found that I could use pip, so I documented it and I also made it more consistent in style.
=> Update Development Instructions

docs/module-sources.rst
This will be expanded when there is a separate page for module properties
=> module-sources: Note that only-arch doesn't restrict other sources

docs/hosting-a-repository.rst
You can see this in action in https://gitlab.com/projects261/firefox-nightly-flatpak
=> hosting: Add an example workflow for building multiple arches 

docs/manifests.rst
Fixes https://github.com/flatpak/flatpak-docs/issues/491
=> manifest: Improve the cleanup section and recommend building less

.github/workflows/docs.yml
=> Update workflows to latest releases

docs/extension.rst
Just the extension needs to be declared.
=> extension: Fix some wording on bundled extension

docs/sandbox-permissions.rst
=> Clarify ownership of mpris name

docs/conf.py, docs/flatpak-devel.rst, docs/index.rst
Fixes https://github.com/flatpak/flatpak-docs/issues/4 
Fixes https://github.com/flatpak/flatpak-docs/issues/13
=> Add docs on using flatpak as a developer platform

docs/under-the-hood.rst
Closes https://github.com/flatpak/flatpak-docs/issues/158
=> under-the-hood: Add link to blog post explaining the Flatpak repo

docs/debugging.rst
See https://lore.kernel.org/linux-perf-users/172196001664.6.11995879867204963322.389309805@slmail.me/T/#t
=> debugging: Add info on perf to get it working with sandbox

docs/first-build.rst
This should help beginners understand better what is happening on the manifest.
=> Explains GNU Coreutils install command and flags on simple build system and links to docs

docs/sandbox-permissions.rst
See  https://github.com/flatpak/flatpak/pull/5855
=> sandbox-permissions: Document the USB devices permission

.github/workflows/update-flatpak-builder-docs.yml, .github/workflows/update-flatpak-docs.yml
So that it creates new branches on each run. Otherwise it is a force push to old branch
=> ci: Change branch startegy to random

docs/basic-concepts.rst
@bbhtt Part of a long-haul polishing effort.
Changes:
- Clearer description of delta updates.
- More concise expressions or precise nouns (e.g. things -> resources)
- Punctuation
- Other changes to be reverted if need be
Line 70 has multiple uses of "object" although the word is almost never used elsewhere with the same meaning throughout the docs. I think it needs a more approachable replacement or an explanation (`object, which is...`).
=> Polish basic-concepts.rst

docs/sandbox-permissions.rst
Needs a bit more editing. 
The feature has landed in flatpak.
=> usb portal documentation

po/de/LC_MESSAGES/available-runtimes.po, po/es/LC_MESSAGES/available-runtimes.po, po/fr/LC_MESSAGES/available-runtimes.po, po/ko/LC_MESSAGES/available-runtimes.po, po/pt_BR/LC_MESSAGES/available-runtimes.po, po/ru/LC_MESSAGES/available-runtimes.po, po/zh_CN/LC_MESSAGES/available-runtimes.po
For ab31dca0a5f160893048432c3311041fc9af7e3d
=> Update po files

.github/workflows/update-flatpak-builder-docs.yml, .github/workflows/update-flatpak-docs.yml
The PPA hasn't been updated for a while
=> ci: Switch docs workflows to Archlinux packages

docs/flatpak-devel.rst
=> Fix spelling error in flatpak-devel.rst
