flatpak/flatpak-docs

docs/building-simple-apps.rst, docs/flatpak-builder.rst
The readme is using org.gnome.Dictionary 3.22 xz and it should be 3.20. Note that the sha256sum in `flatpak-builder.rst` matches dictionary 3.20. Also removed trailing whitespace (good catch Atom).
I found this while reading through http://flatpak.org/developer.html, I think this is the correct repo to update that site.
=> Fix typo: Use org.gnome.Dictionary 3.20

docs/flatpak-builder.rst
I'm not sure what best to do about the link to gnome-apps-nightly now that it's just a series of references to manifests in other repos…
=> builder: update link to Dictionary manifest

docs/_static/flatpak-docs.html, docs/introduction.rst
This adds flatpak-docs.html to the readthedocs website.
The flatpak-docs.html file is generated in the flatpak
repository, by using make html.
=> Add the man pages to the website

docs/working-with-the-sandbox.rst
The command to permanently override a sandbox permission is `flatpak override`,
not `flatpak run`.
=> Fix typo on the "override" section

po/fr/LC_MESSAGES/building-simple-apps.po, po/fr/LC_MESSAGES/command-reference.po, po/fr/LC_MESSAGES/distributing-applications.po, po/fr/LC_MESSAGES/elements-of-a-flatpak-app.po, po/fr/LC_MESSAGES/flatpak-builder.po, po/fr/LC_MESSAGES/getting-setup.po, po/fr/LC_MESSAGES/index.po, po/fr/LC_MESSAGES/introduction.po, po/fr/LC_MESSAGES/working-with-the-sandbox.po
flatpak documentation translated in French.
it remains some sentences to translate because there is need to translate them because they contain only technical information (bug yet to be open for that)
=> French translation for flatpak documentation

docs/working-with-the-sandbox.rst
The rst processor at Read The Docs transforms `--` (two hyphens) into `–` (en dash), which is a common web typography thing to do.
We don't want that here though, otherwise people can't just copy-paste from the docs.
Marking those strings as inline code fixes that.
In addition, one string was already marked as inline code, but was using the en dash in its source, which this commit also fixes.
=> Fix CLI arguments

docs/flatpak-builder.rst
We were missing a few steps in case the reader was directly using flatpak-builder withouth going first to previous charters.
=> flatpak-builder.rst: Fix using flatpak-builder withouth previous charters

docs/flatpak-docs.html
This copies the flatpak-docs.html file generated in the doc folder of
flatpak.git
=> Update the man pages to 0.10.1

docs/flatpak-builder-command-reference.rst, docs/flatpak-builder-docs.html, docs/index.rst
This adds flatpak-builder-docs.html which is generated in
flatpak-builder.git, and adds a page for it since flatpak-builder
was split off into its own repo since the last time the command
reference was updated.
=> Add flatpak-builder command reference

docs/available-runtimes.rst, docs/index.rst
This is a port of the page that is currently hosted on
flatpak.org. It is logical to keep all the information for
developers together, as part of the docs.
=> add a page on available runtimes

docs/first-flatpak.rst, docs/index.rst
We're in the process of consolidating all the developer docs in
flatpak-docs, so move the hello world tutorial over from
flatpak.org.
When I tested the tutorial, running the app returned:
`/usr/bin/echo: /usr/bin/echo: cannot execute binary file`
I'm not sure what the issue is there.
=> add hello world tutorial

docs/flatpak-builder.rst, docs/getting-setup.rst
The examples were using the gnome-apps remote and the GNOME 3.22
runtime and SDK. Update these to use flathub and GNOME 3.26.
=> Update examples to use recent versions

docs/single-file-bundles.rst
Mentioning only that bundles can be imported into repositories makes users 
assume that's a necessary step in order to install the bundle, which may not
be a desirable step for end users who only wish to install the application.
=> Mention that single file bundles can be installed

docs/flatpak-builder-tutorial.rst
The example command calls it tutorial-repo, but the explanation refers to it as just repo.
=> Make repo name consistent with example command

docs/electron.rst
Alternatively, it may be good to drop the build options from the guide altogether and document them somewhere else.
npm has nine log levels that can be used to control which errors get logged, all could be used here, but an electron developer would already be familiar with this.
Maybe the important thing is to inform the user that they can set build-time environment variables in the build options, however, this isn't electron specific. It may make more sense to explain this in a more general build system guide.
=> Add explanation of build options

docs/electron.rst
Otherwise the build could fail because the contents of generated-sources.json wouldn't exactly match those of the bundled package-lock.json.
=> electron.rst -- Build version 1.0.1

docs/building-introduction.rst, docs/building.rst, docs/dependencies.rst, docs/first-build.rst, docs/flatpak-builder.rst
The old first build tutorial used a hello-world script rather
than an prexisting app. The steps for creating a manifest were
useful for showing how Flatpak works.
This commit reinstates the old hello-world-based tutorial. Some
restructuring is necessary as a result.
=> Reinstate the old first build tutorial

docs/electron.rst
Among other dependency changes, electron2 has switched to gtk3 and a new base app has been added for it on flathub. The guide should reflect this.
=> electron.rst - mention electron2 baseapp

docs/conventions.rst, docs/desktop-integration.rst, docs/index.rst
Targeting the Linux desktop ecosystem can be daunting. We should
try and make it easier.
=> Add a page on desktop integration

docs/conventions.rst
Without categories, the apps doesn't get sorted in the right
place in flathub.
https://github.com/flatpak/flatpak-docs/issues/132
=> Add categories to minimal desktop file

docs/manifests.rst
The local directory source option not being in the list in manifests doc, it is hard to discover unless you browse the Flatpak Builder command reference. Let's have it listed just like the rest of the options.
=> manifests.rst: Add dir option to sources list

docs/first-build.rst
This question pops up frequently in the irc channel, it's a common hurdle for new users.
They test using --run and everything is fine, but their application inexplicably breaks when they do the final build.
It may be better to modify flatpak-builder so that --run works in the expected way, but in the mean time it'll be helpful to new users if this is explained.
=> first-build.rst -- add disclaimer about --run

docs/first-build.rst
Installed runtime in:
```bash
$ flatpak install flathub org.freedesktop.Platform//18.08 org.freedesktop.Sdk//18.08
```
is `18.08`, changing manifest example to reflect that.
=> Changing `runtime-version` in manifest codeblock.

docs/manifests.rst
https://blogs.gnome.org/alexl/2018/05/04/yamling-the-flathub/ claims flatpak-builder supports YAML starting with version 0.10.10
=> Mention that YAML is also supported for manifests

docs/desktop-integration.rst, docs/portals-gtk.rst
Add a page that points out specific apis to use for transparent portal support.
Closes: #166
=> Add details about GTK portal support

docs/_static/theme_overrides.css
This makes headings easier to read.
=> Use a bolder font for headings

docs/basic-concepts.rst
I am not sure I am correct, but from what I am learned, a flatpak can't use any libraries in the distribution.
So I guess this is small typos in this chapter?
=> Minor fix for basic concepts chapter

docs/_static/theme_overrides.css, docs/conf.py
- Load stylesheets in `conf.py` instead of using `@import` to make parallel requests possible
- Don't import `sphinx_rtd_theme.css` as it's already loaded by the theme
- Source both web fonts using a single request to Google Fonts
- Use `display: swap` in Web fonts for faster display
=> Optimize CSS delivery

docs/conventions.rst
The extra-data feature is lightly documented but very commonly used when
packaging nonfree applications.
This should fix #159 and partially clarify #53
=> conventions.rst -- Explain extra-data exporting

docs/first-build.rst
Without the specified command the package won't show up in application stores when tested with a local repo.
=> Add information on application store visibility

docs/first-build.rst
It's confusing if here we say that flatpak-builder --run doesn't use the
same permissions as the final app, but in the man page it says that
--run does use the same permissions. So update the wording here to be
more specific.
=> docs/first-build.rst: Clarify --run permissions

docs/building-introduction.rst, docs/electron.rst, docs/manifests.rst, docs/sandbox-permissions-reference.rst, docs/sandbox-permissions.rst, docs/under-the-hood.rst
This PR provides the following fixes:
- **Fix indentation in footnote and bullet list**, so texts in new line be correctly considered as part of its footnote/bullet list (this messes strings in translation as well)
- **Fix warning of duplicate explicit target name**, caused by OSTree URL collision
- **Fix json code-block syntax**, so json code blocks are properly displayed with json syntax highlighting
=> Fixes syntax of bullet list, footnote, json highlighting and duplicate target name

docs/building-introduction.rst
This PR fixes a grammar error and formatting error on the "Building Introduction" article in the docs.
=> Fixed formatting issue with Building Introduction article

docs/sandbox-permissions-reference.rst
I was surprised that "all files" didn't mean literally all files. So as to avoid confusion to other readers who like me, might either land directly on this link instead of navigating away from [here](https://docs.flatpak.org/en/latest/sandbox-permissions.html#filesystem-access) or who just fail to notice the blacklist on one page and only read "all files" on the second one.
=> Clarify "all files"

docs/manifests.rst
The "first build" page doesn't mention the GNOME Dictionary manifest.
=> manifests.rst: typos and wrong manifest reference

.github/workflows/build.yml, requirements.txt
This PR adds a GitHub Actions workflow file `.github/workflows/build.yml` that runs on every `push` and `pull_request` event. 
This workflow will be ran when a member pushes a change to the repository, and also when a pull request is opened, synchronized and reopened<sup>[[1]](https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request)</sup>.
What does this workflow do: 1) set up a cache dir between workflow runs, 2) checkout flatpak-docs master branch, 3) install dependencies via pip, 4) build the documentation treating warnings as errors, 5) upload built documentation as artifacts
This PR also adds a badge to README.rst for better monitoring this workflow's status.
[1] https://help.github.com/en/actions/reference/events-that-trigger-workflo …
=> workflow: add build CI on push/pull_request

docs/guides.rst, docs/qt.rst
Maybe tried to be too non-verbose, please tell me what you'd like to see on it.
=> Qt Flatpak-Builder guide

docs/under-the-hood.rst
These days Flatpak can use OCI to store flatpaks instead of using
ostree; make that clear.
=> under-the-hood: Clarify use of OCI format

docs/desktop-integration.rst
This is a topic that can be confusing for newcomers to the subject, so it definitely has a place in the docs. To create it, I used [TingPing's blog post on the subject](https://tingping.github.io/2017/05/11/flatpak-theming.html), along with some elements from [a related OmgUbuntu article](http://www.omgubuntu.co.uk/2017/05/flatpak-theme-issue-fix), both as processed by my current understanding of the subject, added an up-to-date list of currently available Flatpak theme packages and rephrased some things in order to make them clearer (but still left the "developese" phrases there, as they will probably be useful to developers).
Let me know in case anything needs fixing. Thanks in advance for understanding.
=> Add a page on theming flatpak

docs/available-runtimes.rst
KDE has changed it's link to the Flatpak Runtime repository, from [`kde/flatpak-kde-runtime`](https://invent.kde.org/kde/flatpak-kde-runtime) to [`packaging/flatpak-kde-runtime`](https://invent.kde.org/packaging/flatpak-kde-runtime).
This pull-request modifies the link to the above to reflect the present repository location.
=> Update KDE link in available-runtimes

docs/guides.rst, docs/multiarch.rst
Flatpak provides full multiarch support, but it's usage is not straightforward. This page should cover most common scenarios.
=> Add guide for multilib apps

docs/electron.rst
I spend a few hours trying to figure out why electron-builder was trying to download additional binaries. I think the text could clear up some things about the `--dir` option not always working and what electron-builder interprets in `package.json`
=> electron.rst: Add section about "build"-block in package.json

docs/under-the-hood.rst
according to https://github.com/containers/bubblewrap/issues/233 and as it's already stated as a feature of systemd
=> Small correction: Bubblewrap doesn't use cgroups

docs/freedesktop-quick-reference.rst
The old example was wrong. See discussion here:
https://discourse.flathub.org/t/desktop-files-and-the-exec-line/2322
I hope the new version is not _too_ verbose, but it would definitely have saved me a few hours of debugging my Flatpak app config.
=> Fix and improve docs about Exec line in desktop files

docs/desktop-integration.rst
This makes the global menu information more agnostic, fixes the name for the GTK property, and includes links to the required APIs to make global menus work.
=> Improve global menu description

docs/tips-and-tricks.rst
This improves the package downgrade documentation by explaining how to downgrade packages that were installed per-user.
This fixes issue https://github.com/flatpak/flatpak-docs/issues/220
=> Explain downgrade of per-user installs

docs/conf.py
The use of html_context = {'css_files': []} replaces stylesheets provided by default (pygments.css and css/theme.css), which causes the generated documentation to be unformatted due to incomplete CSS specification.
There's recomendation of using app.add_stylesheet('file.css'), but it is deprecated since 1.8.0, was going to removed in Sphinx 4.0 and then it was postponed to Sphinx 6.0.
Now, html_css_files = [] was added in 1.8.0 to append CSS files, and will fix badly formatted docs by including flatpak-docs stylesheets to the default CSS stylesheets.
Closes: #361
=> Migrate html_context.css_files to html_css_files

.github/matchers/sphinx-linkcheck-warn.json, .github/matchers/sphinx-linkcheck.json, .github/matchers/sphinx.json, .github/workflows/build.yml, .github/workflows/docs.yml
- Tweak SPHINXOPTS removing quiet (`-q`) and enabling nit-picky mode (`-n`) and always write output files (`-a`); see [sphinx-build man page](https://www.sphinx-doc.org/en/master/man/sphinx-build.html)
- Add Sphinx matchers to create annotations of warnings and errors generated in the workflow run
- Add linkcheck job to warn about redirected links (which would be good to fix) and err on broken links (which must be fixed)
- Rename workflow filename build -> docs (it also check links, so "build" doesn't say it all), rename artifact filename
- Set permission to read-only, to improve security denying any malicious write attempt in the workflow run
=> Improve CI

docs/desktop-integration.rst
https://developer.gnome.org was rewritten with new documentation, so https://developer.gnome.org/SerchProvider doesn't exists and is redirected to the home page. While the page itself should be updated, this proposal works around the issue by changing the URL to point to the old docs in https://developer-old.gnome.org
=> Fix link to SearchProvider in GNOME docs

docs/first-build.rst
I just made a PR to the Flathub and I got the feedback that I should use version 22.08 of the SDK instead of 21.08, so I thought it might be good to have that version in the getting started documentation as well.
=> Use sdk version 22.08

docs/manifests.rst
I also went ahead an changed the wordage on the `dir` source type to be plural, since it appeared that the other types were already plural.
=> Fix incorrect wordage for 'file' source types

docs/hosting-a-repository.rst
See https://github.com/flathub/documentation/pull/134 Current docs for self-hosting are very outdated and lacking. The idea is to provide a simple template that people can expand upon.
=> Provide docs for self hosting repo in Gitlab pages

docs/electron.rst
These are used enough to be documented somewhere.
I threw in enough warnings to stick with the default.
=> electron: Document native wayland flags

README.rst, docs/conf.py, requirements.txt
This makes sharing the docs also show a nice preview image etc
=> Add opengraph plugin

docs/conf.py
This is needed, as the image folder for the social images would be expected in the wrong path.
Hopefully the last missing piece
=> Add locale and version to opg site url

docs/extension.rst
- explain add-ld-path
- explain .debug and .locale extensions are created with autodelete=true
- Fix version of an extension
=> extensions: Minor fixes and additions

docs/conventions.rst
This is blocked on Flathub since https://github.com/flathub-infra/flatpak-builder-lint/pull/245
=> conventions: Add a note that composing does not work with extra-data exporting

docs/conf.py, docs/electron.rst
This documents the new `patch-desktop-filename `script in the Electron BaseApp introduced in flathub/org.electronjs.Electron2.BaseApp#56. It also describes how to make the UnityLauncherAPI work.
Fell free to correct my wording, as English is not my native language.
=> Document additions in Electron BaseApp

docs/electron.rst
Followup to https://github.com/flatpak/flatpak-docs/pull/444
The setBadgecount link was pointing to the wrong docs too.
=> electron: Fix some wording and change links to English locale

docs/conf.py
See https://www.sphinx-doc.org/en/master/usage/extensions/autosectionlabel.html
This is useful when referring to arbitrary sections in a different document.
`autosectionlabel_prefix_document` is used to add a file prefix to each label and resolve duplicate label warnings as labels are global.
=> conf: Label sections automatically

docs/sandbox-permissions.rst
`host` is a superset of `host-etc` and `host-os`
Fixes https://github.com/flatpak/flatpak-docs/issues/480
This broke during combining the sandbox-reference page with this one.
=> sandbox-permissions: Fix access docs for host filesystem permission

docs/building.rst, docs/conventions.rst, docs/manifests.rst, docs/module-sources.rst
This needs a place somewhere under Building, I placed it under guides temporarily as I can't figure out a proper place without restructuring.
=> Add docs for various source types

docs/Makefile
And fallback to `sphinx-build-3` only if it does not exist.
The default build instructions now use a python virtual environment and inside that pip installs `sphinx-build`. Since the `<venv>/bin` is exported as the first item in `$PATH` once activated, we can ensure that `sphinx-build` from venv is used first.
Outside the venv if `sphinx-build` is not found `sphinx-build-3` is tried.
Closes https://github.com/flatpak/flatpak-docs/issues/477
=> Makefile: Use sphinx-build as the default sphinx command

docs/module-sources.rst
These can be URL or git or whatever. `file` has a specific meaning here
=> module-sources: Remove "file" restriction for metadata in extra-data

docs/sandbox-permissions.rst
This is a spin off #478 
It's current. I will rebase #478 on top of this.
=> sandbox-permissions: Document the device permissions

docs/introduction.rst
Replaces double usage of the word 'suited' in 'Flatpak is best suited suited for desktop'.
=> Fix typo at introduction.rst

docs/first-build.rst
Addresses most of the things in https://github.com/flatpak/flatpak-docs/issues/230, so closes https://github.com/flatpak/flatpak-docs/issues/230
This simplifies the first build guides and reduces possible failure points.
- script is self-contained in the manifest
- build and install instructions combined to avoid running multiple commands
- Add ``--install-deps-from`` to avoid figuring out installing runtimes
- Removes creating a repo - not sure why this is in a hello world guide. Exporting it to a repo has no direct use cases since it can be installed with flatpak-builder directly and the section references more complicated topics such as appdata files, `build-update`, `gpg-verify` etc. that need not be in a hello world guide.
So I replaced it with sharing a single file bundle, which …
=> Simplify the first build guide

docs/electron.rst
Messing with `XDG_CURRENT_DESKTOP` is a bad idea as that env var used to often find the proper trash cli gio/kio etc. And it is also fixed from v32 (unreleased) https://github.com/electron/electron/pull/41211
=> electron: Remove recommendation for setting XDG_CURRENT_DESKTOP

docs/sandbox-permissions.rst
This is a follow-up of https://github.com/flatpak/flatpak-docs/pull/471
I would like to make clear how to store data in the best way and when no additional permissions are needed.
Question: Are these variables mapped to in-app directories in the same way during the build?
=> Describe which access does not need additional permissions

docs/module-sources.rst
1 singular instance of "extratced" -> "extracted"
=> Tiny Typo Fix

docs/sandbox-permissions.rst
Hi, I found this typo when changing my flatpak config.
=> Typo: xdg-downloads -> xdg-download

.github/workflows/docs.yml, .github/workflows/update-flatpak-builder-docs.yml, .github/workflows/update-flatpak-docs.yml
This is a workaround because the create-pull-request action uses the repository's GitHub token and cannot trigger further workflow runs.
See https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs
opened, edited, synchronize are the default; reopened is for convenience
Add ready_for_review as per the recommendation here https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs
=> ci: Create draft PRs by action and set PR types

docs/extension.rst, docs/flatpak-devel.rst
See [the log](https://github.com/flatpak/flatpak-docs/actions/runs/11061706291/job/30734825416?pr=529) of linkcheck job. Specifically:
> (       extension: line  570) redirect  https://github.com/KhronosGroup/Vulkan-Guide/blob/master/chapters/layers.md - with Found to https://github.com/KhronosGroup/Vulkan-Guide/blob/main/chapters/layers.md
> (   flatpak-devel: line  368) broken    https://www.electron.build/configuration/flatpak.html - 404 Client Error: Not Found for url: https://www.electron.build/configuration/flatpak.html
=> Fix issues reported by linkcheck

README.rst, docs/Makefile, requirements.txt
This allows to run `make update-po` to 1) generate POT files, 2) update all PO files using the newly generated POT files, 3) remove obsolete PO files that might still be in the PO file.
Also updates the README with the new command, besides using `make` to build translated docs.
=> Add update-po Makefile target

.github/workflows/update-flatpak-builder-docs.yml, .github/workflows/update-flatpak-docs.yml
without this the update-failed step does not run
=> ci: Add continue-on-error

docs/portals.rst
apparently this contradicting sentence got overlooked in https://github.com/flatpak/flatpak-docs/commit/b18084c9dcf97d9d8a119887708db70a46cc193f
=> Correct portals.rst

docs/introduction.rst
@bbhtt Part of a long-haul effort of mine to polish the English documentation before translation.
Changes:
- A clearer terminology section, especially for `Runtime` and `BaseApp`. The use of `platform` can be vague and unclear for beginners. (Defining something "also known as platform" as an "integrated platform" is just confusing. Below, `BaseApp` is also an "integrated platform", making their differences hard to grasp.)
- Punctuation, prepositional use (e.g, issue with vs. issue of)
- Most other changes are unnecessary, but I kept them because they seem more concise. I'll revert them if they're deemed unacceptable.
P/s: Also a trivial nitpick-y thing, I think the capitalization of `flatpak` should also have consistent rules. For example, `Flatpak` with a uppercase `F` is used (1) for …
=> Polish introduction.rst

docs/desktop-integration.rst
Polishing `Desktop Integration`. The commits in the previous pull request have been squashed except for the warning label one.
Changes:
- Fix typos
- Punctuation
- Update the link to the libdecor library (now at Freedesktop Gitlab)
- Changing other confusing expressions, especially those concerning the Settings portal and XSettings in the Theming section
- Other grammatical fixes
=> Polish desktop-integration.rst (squashed)

docs/conventions.rst
Polish "Requirements & Conventions".
Changes:
- Punctuation
- Clear up some confusing sentences and use better phrasing
- Other grammatical fixes
=> Polish conventions.rst

docs/electron.rst
I have observed that some users are unable to launch electron based apps due to this missing permission. So, adding this flag in the example
See: https://github.com/flathub/io.frappe.books/issues/1
=> Add --device=dri to the electron packaging example

docs/debugging.rst, docs/sandbox-permissions.rst
Flatpak internally sets up a /var/run to /run symlink https://github.com/flatpak/flatpak/blob/fd1b7e444016d1b44bdab7cb5642b0ac83bd4b9e/common/flatpak-run.c#L2281. If it is symlinked on host too, when using `--filesystem=var/run/subpath` bwrap gets called twice to create the same symlink and the second one will fail.
See also https://github.com/containers/bubblewrap/commit/4109d59251fdb0800cf7e742791ba2b35a1f0f25
=> Add that `/var/run` or subpaths cannot be exposed when symlinked on host

docs/electron.rst
* Add note that WaylandWindowDecorations is not needed after Electron 27 (https://github.com/electron/electron/commit/33000c4)
* Clarify where the correct desktop filename is needed for setProgressBar/setBadgeCount
=> Clarify a couple of Electron instructions

docs/electron.rst, docs/sandbox-permissions.rst
Regarding `XCURSOR_PATH` , see https://github.com/flatpak/flatpak/issues/740#issuecomment-612487891.
=> electron: Overhaul *Sandbox permissions* section

docs/dotnet.rst
It provides bindings for Gtk4 and other GObject libraries.
Should we remove GtkSharp - it is unmaintained since 2023?
=> Add Gir.Core to the list of GUI frameworks
